config/routes.rb
Doandose::Application.routes.draw do
  mount Resque::Server.new, at: "/resque"

  root to: 'pages#index'

  match "/auth/:provider/callback" => "users/sessions#create"
  match '/auth/failure/' => 'users/sessions#failure'
  post '/send_email/' => 'send_mail#create', as: :send_mail
  post '/cadastro/email-em-uso/' => 'people#email_in_use'

  get '/quem_somos/' => 'pages#about_us', as: :about_us
  get '/depoimentos/' => 'testimonials#index', as: :testimonials

  namespace :users, :path => 'usuario' do
    match '/login' => 'sessions#new', as: :new_session
    match '/sair' => 'sessions#destroy', as: :destroy_session

    get  '/cadastro/' => 'identities#new', as: :new_user
    post '/cadastro/' => 'identities#create', as: :new_user
    get  '/meu-cadastro/' => 'identities#edit', as: :edit_user
    put  '/meu-cadastro/' => 'identities#update', as: :edit_user

    get '/esqueci-minha-senha/' => 'passwords#new', as: :new_password
    post '/esqueci-minha-senha/' => 'passwords#create', as: :new_password
    get '/esqueci-minha-senha/:token' => 'passwords#edit', as: :edit_password
    put '/esqueci-minha-senha/:token' => 'passwords#update'
  end

  post '/find_elements_to_map/' => 'gmap#find_elements_to_map'
  post '/find_elements_to_notification/' => 'gmap#find_elements_to_notification'

  resources :people, path: 'usuario' do
    get ':id/page/:page', action: :show, on: :collection
  end

  resources :pages, only: [:index, :show]

  resources :notifications, only: [:index, :show], path: 'notificacoes' do
    get 'page/:page', action: :index, on: :collection
    get :list_user
    get :print
    member do
      get :indication_friend
      post :send_indication
      get :confirm
      get :undo_confirm
      post :confirmed
    end
  end

  resources :campaigns, only: [:index, :show], path: 'campanhas' do
    get 'page/:page', action: :index, on: :collection
    get :print
    member do
      get :undo_confirm
      post :confirmed
    end
  end

  resources :person_notification, only: :index do
    member do
      get :canceling
    end
  end
  resources :companies, only: [:index, :show]
  resources :informations, only: [:show]

  namespace :admin do
    root :to => 'companies#index'
    match '/sair/' => 'base#destroy', as: :destroy_session
    post '/estatistica/cadastro-por-dia/' => 'statistics#subscribe_per_date'
    resources :pages, only: :index
    resources :companies
    resources :bloods
    resources :notifications
    resources :people, except: [:new, :create]
    resources :informations
    resources :campaigns
    get '/estatisticas/' => 'statistics#index', as: :statistics
  end

  namespace :institution, path: 'instituicao' do
    root :to => 'notifications#index'
    get '/sair/' => 'base#destroy', as: :destroy_company_session
    resources :notifications
    resources :campaigns, except: :destroy
    resources :person_notifications, only: :show do
      member do
        post :participation
        post :send_sms
        post :send_email
      end
    end
  end



end

app/models/notification.rb
class Notification
  # Includes
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slugify

  # Fields
  field :active, type: Boolean, default: true
  field :quantity, type: Integer
  field :situation, type: String
  field :title, type: String
  field :observation, type: String
  field :closed_at, type: Time
  field :result, type: String

  # Accessors
  attr_accessor :blood_type, :distance

  # Relationships
  belongs_to :company
  belongs_to :blood
  has_many :person_notifications, dependent: :destroy, autosave: true

  # Access control
  attr_accessible :quantity, :situation, :active, :blood_id, :blood,
    :company_id, :title, :observation, :company, :person_notifications_attributes,
    :blood_type, :distance, :person_notifications

  # Validations
  validates_presence_of :company, :blood, :situation, :quantity, :person_notifications, :title
  validates_presence_of :blood_type, if: :blood_required
  validates_numericality_of :quantity
  validates_inclusion_of :situation, in: %w(urgent moderate)

  # Scopes
  scope :actives, where(active: true)
  scope :compatibles_by, ->(bloods) { where(:blood_id.in => bloods) }

  # Callbacks
  after_create :send_sms, :send_email

  # Others
  def blood_required
    blood.blank? && new_record?
  end

  def send_sms
    Resque.enqueue(Notifications::SMS, self.id)
  end

  def send_email
    Resque.enqueue(Notifications::Email, self.id)
  end

  def will_participate(person)
    person_notifications.by_person(person.id).notification_contains(self.id).first
  end

  def remaining
    quantity - self.person_notifications.count
  end

  def notification_confirmed(user)
     self.person_notifications.by_person( user ).exists?
  end

  private
  def generate_slug
    title.parameterize
  end
end

app/controllers/admin/notifications_controller.rb
class Admin::NotificationsController < Admin::BaseController
  def index
    @notifications = Notification.all
  end

  def new
    @notification = Notification.new
  end

  def show
    @notification = Notification.find_by_slug params[:id]
  end

  def edit
    @bloods = Blood.scoped.map{ |b| [b.name, b.id] }
    @notification = Notification.find_by_slug params[:id]
  end

  def create
    @notification = Notification.new params[:notification]

    position = @notification.company.address.loc
    blood_types = BloodMatch.receives @notification.blood.name

    if blood_types
      people = GMap.elements_by_distance(position, 40, 'Person').map(&:addressable)

      for person in people
        last_participation = person.alerts.participateds.last
        next if last_participation && (last_participation.created_at + 3.months) > Time.now
        if person.blood.name.in? blood_types
          @notification.person_notifications.new person: person
        end
      end
    end

    if @notification.valid?
      if @notification.save
        redirect_to([:admin, :notifications], :notice => t('flash.notification.create.notice'))
      else
        render action: 'new'
      end
    else
      render action: :new
    end

  end

  def update
    @notification = Notification.find_by_slug params[:id]

    if @notification.update_attributes params[:notification]
      redirect_to([:admin, @notification], :notice => t('flash.notification.update.notice'))
    else
      render :action => "edit"
    end
  end

  def destroy
    @notification = Notification.find_by_slug(params[:id])

    if @notification.destroy
      redirect_to [:admin, :notifications], :notice => t('flash.notification.delete.notice')
    else
      redirect_to :action => 'edit'
    end
  end
end

app/controllers/institution/base_controller.rb
class Institution::BaseController < ApplicationController
  before_filter :authenticate_user!
  layout '/layouts/institution'
end

app/controllers/institution/campaigns_controller.rb
class Institution::CampaignsController < Institution::BaseController

  def index
    @campaigns = current_user.authenticable.campaigns
  end

  def show
    @campaign = Campaign.find_by_slug params[:id]
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new params[:campaign]
    @campaign.company_id = current_user.authenticable

    participants_choose

    if @campaign.save
      redirect_to([:institution, :campaigns], :notice => t('flash.campaign.create.notice'))
    else
      render action: :new
    end
  end

  def edit
    @campaign = Campaign.find_by_slug params[:id]
  end

  def update
    @campaign = Campaign.find_by_slug params[:id]

    if @campaign.update_attributes params[:campaign]
      redirect_to institution_campaigns_path
    else
      render 'edit'
    end
  end

  private
    def participants_choose
      position = current_user.authenticable.address.loc
      blood_types = BloodMatch.receives @campaign.blood.name

      if blood_types
        people = GMap.elements_by_distance(position, 40, 'Person').map(&:addressable)
        for person in people
          last_participation = person.alerts.participateds.last
          next if last_participation && (last_participation.created_at + 3.months) > Time.now
          if person.blood.name.in? blood_types
            @campaign.person_campaigns.new person: person
          end
        end
      end
    end
end

app/controllers/institution/notifications_controller.rb
class Institution::NotificationsController < Institution::BaseController

  def index
    @notifications = current_user.authenticable.notifications
  end

  def new
    @notification = Notification.new
  end

  def show
    @notification = Notification.find_by_slug params[:id]
  end

  def create
    @notification = Notification.new params[:notification]

    @notification.company = current_user.authenticable
    @notification.blood = Blood.where( name: @notification.blood_type).first

    position = current_user.authenticable.address.loc
    blood_types = BloodMatch.receives @notification.blood_type

    if blood_types
      people = GMap.elements_by_distance(position, @notification.distance.to_i, 'Person').map(&:addressable)
      for person in people
        last_participation = person.alerts.participateds.last
        next if last_participation && (last_participation.created_at + 3.months) > Time.now

        if person.blood.name.in? blood_types
          @notification.person_notifications.new person: person
        end
      end
    end

    if @notification.valid?
      if @notification.save
        redirect_to([:institution, :notifications], :notice => t('flash.notification.create.notice'))
      else
        render action: :new
      end
    else
      render action: :new
    end
  end

  def destroy
    @notification = Notification.find_by_slug params[:id]

    if @notification.destroy
      redirect_to [:institution, :notifications], :notice => t('flash.notification.delete.notice')
    else
      redirect_to :action => 'edit'
    end
  end
end

app/controllers/institution/pages_controller.rb
class Institution::PagesController < Institution::BaseController
  def index
  end
end

app/controllers/institution/person_notifications_controller.rb
class Institution::PersonNotificationsController < Institution::BaseController
  before_filter :find_person_notification

  def show
  end

  def participation
    @person_notification.update_attributes(participated: params[:participated])
    render nothing: true
  end

  def send_sms
    if @person_notification.can_send_sms
      Resque.enqueue(PersonNotifications::SMS, @person_notification.id)
      flash[:notice] = 'email enviado com sucesso !!!'
    else
      flash[:notice] = 'Ja foi disparado um email para este usuario. Aguarde 1 hr.'
    end
    render nothing: true
  end

  def send_email
    if @person_notification.can_send_email
      Resque.enqueue(PersonNotifications::Email, @person_notification.id)
      flash[:notice] = 'sms enviado com sucesso !!!'
    else
      flash[:notice] = 'Ja foi disparado um sms para este usuario. Aguarde 1 hr.'
    end
    render nothing: true
  end

  private
  def find_person_notification
    @person_notification = PersonNotification.find params[:id]
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  layout '/layouts/print', only: :print
  before_filter :authenticate_user!, only: [:confirm, :confirmed, :undo_confirm]

  def index
    if user_signed_in?
      @notifications = Notification.actives.compatibles_by(Blood.where(:name.in => BloodMatch.donor(current_user.authenticable.blood.name)).map(&:id)).paginate(:page => params[:page])
    else
      @notifications = Notification.actives.paginate(:page => params[:page])
    end
  end

  def show
    @notification = Notification.find_by_slug params[:id]
    @qr_code = RQRCode::QRCode.new( notification_url(@notification), :size => 10, leve: :l )
  end

  def confirm
    @notification = Notification.find_by_slug params[:id]
    @person = current_user.authenticable
    @person_notification = @notification.person_notifications.new
  end

  def confirmed
    @person = current_user.authenticable
    @notification = Notification.find_by_slug params[:id]

    if @notification.notification_confirmed( current_user.authenticable.id )
      update_notification_canceled
      redirect_to notifications_path
    else
      save_confirmed_notification
    end
  end

  def undo_confirm
    @notification = Notification.find_by_slug(params[:id])
    @person_notification = @notification.will_participate(current_user.authenticable)
    if @person_notification.update_attributes(canceled_at: Time.now)
      redirect_to notifications_path
    end
  end

  def list_user
    @notification = Notification.find_by_slug params[:notification_id]
    @person_notifications = @notification.person_notifications
  end

  def indication_friend
    @notification = Notification.find_by_slug params[:id]
    @send_indication = IndicationFriend.new
  end

  def send_indication
    @notification = Notification.find_by_slug params[:id]
    @send_indication = IndicationFriend.new params[:indication_friend]

    if @send_indication.valid?
      Mailer.indication_friend(@send_indication).deliver
      redirect_to notification_path(@notification)
    else
      render action: 'indication_friend'
    end
  end

  def print
    @notification = Notification.find_by_slug params[:notification_id]
    @qr_code = RQRCode::QRCode.new( notification_url(@notification), :size => 10, leve: :l )
  end

  private
    def save_confirmed_notification
      @person_notification = @notification.person_notifications.new params[:person_notification]

      if @person_notification.save
        redirect_to notification_path(@notification)
      else
        p @person_notification.errors
        render action: 'confirm'
      end
    end

    def update_notification_canceled
      @person_notification = @notification.will_participate(current_user.authenticable)

      if @person_notification.canceled?
        @person_notification.update_attributes(canceled_at: '')
      end
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def participate_button(notification)
    if user_signed_in?
      participate = notification.will_participate(current_user.authenticable)
      if participate.present? && participate.non_canceled?
        link_to t('buttons.non_participate'), undo_confirm_notification_path(notification), class: 'button red'
      else
        link_to t('buttons.participate'), confirm_notification_path(notification), class: 'button red'
      end
    else
      link_to t('buttons.participate'), confirm_notification_path(notification), class: 'button red'
    end
  end

  def show_list(count, notification)
    if count.zero?
      count
    else
      link_to count, notification_list_user_path(notification)
    end
  end

  def situations
    [
      ['Urgente', 'urgent'],
      ['Moderado', 'moderate']
    ]
  end

  def parse_time(time)
    time.strftime("%m de %b %Y - %H:%M h")
  end
end

app/views/institution/notifications/_form.html.haml
#gmap

#filters
  #bloods
    - for blood in Blood.scoped
      %span= blood.name

    = error_for(@notification, :blood_type)

  #distances
    .range
    %span.range_value 1

#counter

#result

= form_for @notification, url: institution_notifications_path do |f|
  .form
    = f.text_field :title, placeholder: t('label.title')
    = error_for(@notification, :title)

    = f.text_field :quantity, placeholder: t('label.quantity')
    = error_for(@notification, :quantity)

    = f.label :situation, t('label.situation')
    = f.select :situation, situations
    = error_for(@notification, :situation)

    = f.text_area :observation, placeholder: t('label.title')
    = error_for(@notification, :observation)

    = f.hidden_field :blood_type, class: 'blood'
    = f.hidden_field :distance, class: 'distance'

  .actions
    = f.submit 'salvar', class: 'notification', class: 'button save'

- content_for :javascript do
  :javascript
    new NewNotification()
    new Mask()
    new RemoveFromErrors()

app/views/institution/notifications/_reported.html.haml
%h2 Notificados
%table.list
  %thead
    %tr
      %th= t('label.name')
      %th= t('label.canceled_at')
      %th= t('label.confirmed_at')
      %th= t('label.present')
      %th
  %tbody
    - for person_notification in notification.person_notifications
      %tr
        %td= person_notification.person.name
        %td= person_notification.canceled_at
        %td= person_notification.confirmed_at
        %td= check_box_tag 'participated', person_notification.id, person_notification.participated, class: 'particpated'
        %td
          = link_to 'detalhes', institution_person_notification_path(person_notification), class: 'link show'

- content_for :javascript do
  :javascript
    new Tables()

app/views/institution/notifications/edit.html.haml
%h2= t('views.notifications.title_edit')

= render 'form'

app/views/institution/notifications/index.html.haml
#index
  %h2= t('views.notifications.title')

  = link_to t('buttons.new'), new_institution_notification_path, class: 'button new'

  - unless @notifications.blank?
    %table.list
      %thead
        %tr
          %th= t('label.active')
          %th= t('label.title')
          %th= t('label.quantity')
          %th= t('label.situation')
          %th= t('label.actions')

      %tbody
        - @notifications.each do |notification|
          %tr
            %td= label_boolean(notification.active)
            %td= notification.title
            %td= notification.quantity
            %td
              - for situation in situations
                = situation[0] if situation.include?(notification.situation)

            %td
              = link_to t('buttons.show'), institution_notification_path(notification), class: 'link show'
              = link_to t('form.buttons.delete'), [:institution, notification], confirm: t('flash.advertise'), method: :delete, class: 'link delete'
  - else
    .empty= t('label.empty')

- content_for :javascript do
  :javascript
    new Tables()

app/views/institution/notifications/new.html.haml
%h2= t('views.notifications.title_new')

= render 'form'

app/views/institution/notifications/show.html.haml
#show
  %h2= @notification.title

  .content
    %p
      = label_boolean(@notification.active)
      %b= t('label.active')

    %p
      = @notification.blood.name
      %b= t('label.blood')

    %p
      = @notification.title
      %b= t('label.title')

    %p
      = @notification.quantity
      %b= t('label.quantity')

    %p
      - for situation in situations
        = situation[0] if situation.include?(@notification.situation)
      %b= t('label.situation')

    %p
      = @notification.observation
      %b= t('label.observation')

    %p
      = @notification.company.name
      %b= t('label.company')

  = render partial: 'institution/notifications/reported', locals: { notification: @notification }

  .actions
    = link_to t('buttons.back'), institution_notifications_path, :class => 'link back'
    = link_to t('buttons.delete'), [:institution, @notification], method: :delete, confirm: t('flash.advertise'), :class => "link delete"

- content_for :javascript do
  :javascript
    new ShowNotification()