config/routes.rb
Doandose::Application.routes.draw do
  mount Resque::Server.new, at: "/resque"

  root to: 'pages#index'

  match "/auth/:provider/callback" => "users/sessions#create"
  match '/auth/failure/' => 'users/sessions#failure'
  post '/send_email/' => 'send_mail#create', as: :send_mail
  post '/cadastro/email-em-uso/' => 'people#email_in_use'

  get '/quem_somos/' => 'pages#about_us', as: :about_us
  get '/depoimentos/' => 'testimonials#index', as: :testimonials

  namespace :users, :path => 'usuario' do
    match '/login' => 'sessions#new', as: :new_session
    match '/sair' => 'sessions#destroy', as: :destroy_session

    get  '/cadastro/' => 'identities#new', as: :new_user
    post '/cadastro/' => 'identities#create', as: :new_user
    get  '/meu-cadastro/' => 'identities#edit', as: :edit_user
    put  '/meu-cadastro/' => 'identities#update', as: :edit_user

    get '/esqueci-minha-senha/' => 'passwords#new', as: :new_password
    post '/esqueci-minha-senha/' => 'passwords#create', as: :new_password
    get '/esqueci-minha-senha/:token' => 'passwords#edit', as: :edit_password
    put '/esqueci-minha-senha/:token' => 'passwords#update'
  end

  post '/find_elements_to_map/' => 'gmap#find_elements_to_map'
  post '/find_elements_to_notification/' => 'gmap#find_elements_to_notification'

  resources :people, path: 'usuario' do
    get ':id/page/:page', action: :show, on: :collection
  end

  resources :pages, only: [:index, :show]

  resources :notifications, only: [:index, :show], path: 'notificacoes' do
    get 'page/:page', action: :index, on: :collection
    get :list_user
    get :print
    member do
      get :indication_friend
      post :send_indication
      get :confirm
      get :undo_confirm
      post :confirmed
    end
  end

  resources :campaigns, only: [:index, :show], path: 'campanhas' do
    get 'page/:page', action: :index, on: :collection
    get :print
    member do
      get :undo_confirm
      post :confirmed
    end
  end

  resources :person_notification, only: :index do
    member do
      get :canceling
    end
  end
  resources :companies, only: [:index, :show]
  resources :informations, only: [:show]

  namespace :admin do
    root :to => 'companies#index'
    match '/sair/' => 'base#destroy', as: :destroy_session
    post '/estatistica/cadastro-por-dia/' => 'statistics#subscribe_per_date'
    resources :pages, only: :index
    resources :companies
    resources :bloods
    resources :notifications
    resources :people, except: [:new, :create]
    resources :informations
    resources :campaigns
    get '/estatisticas/' => 'statistics#index', as: :statistics
  end

  namespace :institution, path: 'instituicao' do
    root :to => 'notifications#index'
    get '/sair/' => 'base#destroy', as: :destroy_company_session
    resources :notifications
    resources :campaigns, except: :destroy
    resources :person_notifications, only: :show do
      member do
        post :participation
        post :send_sms
        post :send_email
      end
    end
  end



end

app/models/blood.rb
class Blood
  # Includes
  include Mongoid::Document
  include Mongoid::Slugify

  # Fields
  field :name, type: String

  # Relationships
  has_many :people
  has_many :notifications

  # Validations
  validates_presence_of :name
  validates_uniqueness_of :name

  # Other
  private
  def generate_slug
    name.parameterize
  end

end

app/controllers/admin/bloods_controller.rb
class Admin::BloodsController < Admin::BaseController
  def index
    @bloods = Blood.all
  end

  def new
    @blood = Blood.new
  end

  def edit
    @blood = Blood.find_by_slug params[:id]
  end

  def create
    @blood = Blood.new params[:blood]

    if @blood.save
      redirect_to [:admin, :bloods], :notice => t('flash.blood.create.notice')
    else
      render :action => "new"
    end
  end

  def update
    @blood = Blood.find_by_slug params[:id]

    if @blood.update_attributes(params[:blood])
      redirect_to [:admin, :bloods], :notice => t('flash.blood.update.notice')
    else
      render :action => "edit"
    end
  end

  def destroy
    @blood = Blood.find_by_slug params[:id]
    @blood.destroy
    redirect_to [:admin, :bloods], :notice => t('flash.blood.delete.notice')
  end
end

app/controllers/bloods_controller.rb
class BloodsController < ApplicationController
end

app/views/admin/bloods/_form.html.haml
.form
  = f.text_field :name, placeholder: t('label.name')
  = error_for(@blood, :name)

= link_to t('buttons.back'), [:admin, :bloods], class: 'back_form'

.actions
  = f.button :submit, t('buttons.save'), class: 'button save'

  - unless @blood.new_record?
    = link_to t('buttons.delete'), [:admin, @blood], method: :delete, confirm: t('flash.advertise'), class: 'button delete'

- content_for :javascript do
  :javascript
    new RemoveFromErrors()

app/views/admin/bloods/edit.html.haml
%h2= t('views.blood.title')

= simple_form_for @blood, :url => [:admin, @blood] do |f|
  = render :partial => 'form', :locals => { :f => f }

app/views/admin/bloods/index.html.haml
#index
  %h2= t('views.blood.title_index')
  = link_to t('buttons.new'), new_admin_blood_path, class: 'button new'

  - unless @bloods.blank?
    %table.list
      %thead
        %tr
          %th= t('label.name')
          %th= t('label.actions')
      %tbody
        - for blood in @bloods
          %tr
            %td= blood.name
            %td
              = link_to t('buttons.edit'), edit_admin_blood_path(blood), class: 'link edit'

              = link_to t('buttons.delete'), [:admin, blood], method: :delete, confirm: t('flash.advertise'), class: 'link delete'

  - else
    .empty= t('label.empty')

- content_for :javascript do
  :javascript
    new Tables()

app/views/admin/bloods/new.html.haml
%h2= t('views.blood.title_new')

= simple_form_for @blood, :url => [:admin, @blood] do |f|
  = render :partial => 'form', :locals => { :f => f }