config/routes.rb
Doandose::Application.routes.draw do
  mount Resque::Server.new, at: "/resque"

  root to: 'pages#index'

  match "/auth/:provider/callback" => "users/sessions#create"
  match '/auth/failure/' => 'users/sessions#failure'
  post '/send_email/' => 'send_mail#create', as: :send_mail
  post '/cadastro/email-em-uso/' => 'people#email_in_use'

  get '/quem_somos/' => 'pages#about_us', as: :about_us
  get '/depoimentos/' => 'testimonials#index', as: :testimonials

  namespace :users, :path => 'usuario' do
    match '/login' => 'sessions#new', as: :new_session
    match '/sair' => 'sessions#destroy', as: :destroy_session

    get  '/cadastro/' => 'identities#new', as: :new_user
    post '/cadastro/' => 'identities#create', as: :new_user
    get  '/meu-cadastro/' => 'identities#edit', as: :edit_user
    put  '/meu-cadastro/' => 'identities#update', as: :edit_user

    get '/esqueci-minha-senha/' => 'passwords#new', as: :new_password
    post '/esqueci-minha-senha/' => 'passwords#create', as: :new_password
    get '/esqueci-minha-senha/:token' => 'passwords#edit', as: :edit_password
    put '/esqueci-minha-senha/:token' => 'passwords#update'
  end

  post '/find_elements_to_map/' => 'gmap#find_elements_to_map'
  post '/find_elements_to_notification/' => 'gmap#find_elements_to_notification'

  resources :people, path: 'usuario' do
    get ':id/page/:page', action: :show, on: :collection
  end

  resources :pages, only: [:index, :show]

  resources :notifications, only: [:index, :show], path: 'notificacoes' do
    get 'page/:page', action: :index, on: :collection
    get :list_user
    get :print
    member do
      get :indication_friend
      post :send_indication
      get :confirm
      get :undo_confirm
      post :confirmed
    end
  end

  resources :campaigns, only: [:index, :show], path: 'campanhas' do
    get 'page/:page', action: :index, on: :collection
    get :print
    member do
      get :undo_confirm
      post :confirmed
    end
  end

  resources :person_notification, only: :index do
    member do
      get :canceling
    end
  end
  resources :companies, only: [:index, :show]
  resources :informations, only: [:show]

  namespace :admin do
    root :to => 'companies#index'
    match '/sair/' => 'base#destroy', as: :destroy_session
    post '/estatistica/cadastro-por-dia/' => 'statistics#subscribe_per_date'
    resources :pages, only: :index
    resources :companies
    resources :bloods
    resources :notifications
    resources :people, except: [:new, :create]
    resources :informations
    resources :campaigns
    get '/estatisticas/' => 'statistics#index', as: :statistics
  end

  namespace :institution, path: 'instituicao' do
    root :to => 'notifications#index'
    get '/sair/' => 'base#destroy', as: :destroy_company_session
    resources :notifications
    resources :campaigns, except: :destroy
    resources :person_notifications, only: :show do
      member do
        post :participation
        post :send_sms
        post :send_email
      end
    end
  end



end

app/models/notification.rb
class Notification
  # Includes
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slugify

  # Fields
  field :active, type: Boolean, default: true
  field :quantity, type: Integer
  field :situation, type: String
  field :title, type: String
  field :observation, type: String
  field :closed_at, type: Time
  field :result, type: String

  # Accessors
  attr_accessor :blood_type, :distance

  # Relationships
  belongs_to :company
  belongs_to :blood
  has_many :person_notifications, dependent: :destroy, autosave: true

  # Access control
  attr_accessible :quantity, :situation, :active, :blood_id, :blood,
    :company_id, :title, :observation, :company, :person_notifications_attributes,
    :blood_type, :distance, :person_notifications

  # Validations
  validates_presence_of :company, :blood, :situation, :quantity, :person_notifications, :title
  validates_presence_of :blood_type, if: :blood_required
  validates_numericality_of :quantity
  validates_inclusion_of :situation, in: %w(urgent moderate)

  # Scopes
  scope :actives, where(active: true)
  scope :compatibles_by, ->(bloods) { where(:blood_id.in => bloods) }

  # Callbacks
  after_create :send_sms, :send_email

  # Others
  def blood_required
    blood.blank? && new_record?
  end

  def send_sms
    Resque.enqueue(Notifications::SMS, self.id)
  end

  def send_email
    Resque.enqueue(Notifications::Email, self.id)
  end

  def will_participate(person)
    person_notifications.by_person(person.id).notification_contains(self.id).first
  end

  def remaining
    quantity - self.person_notifications.count
  end

  def notification_confirmed(user)
     self.person_notifications.by_person( user ).exists?
  end

  private
  def generate_slug
    title.parameterize
  end
end

app/controllers/admin/notifications_controller.rb
class Admin::NotificationsController < Admin::BaseController
  def index
    @notifications = Notification.all
  end

  def new
    @notification = Notification.new
  end

  def show
    @notification = Notification.find_by_slug params[:id]
  end

  def edit
    @bloods = Blood.scoped.map{ |b| [b.name, b.id] }
    @notification = Notification.find_by_slug params[:id]
  end

  def create
    @notification = Notification.new params[:notification]

    position = @notification.company.address.loc
    blood_types = BloodMatch.receives @notification.blood.name

    if blood_types
      people = GMap.elements_by_distance(position, 40, 'Person').map(&:addressable)

      for person in people
        last_participation = person.alerts.participateds.last
        next if last_participation && (last_participation.created_at + 3.months) > Time.now
        if person.blood.name.in? blood_types
          @notification.person_notifications.new person: person
        end
      end
    end

    if @notification.valid?
      if @notification.save
        redirect_to([:admin, :notifications], :notice => t('flash.notification.create.notice'))
      else
        render action: 'new'
      end
    else
      render action: :new
    end

  end

  def update
    @notification = Notification.find_by_slug params[:id]

    if @notification.update_attributes params[:notification]
      redirect_to([:admin, @notification], :notice => t('flash.notification.update.notice'))
    else
      render :action => "edit"
    end
  end

  def destroy
    @notification = Notification.find_by_slug(params[:id])

    if @notification.destroy
      redirect_to [:admin, :notifications], :notice => t('flash.notification.delete.notice')
    else
      redirect_to :action => 'edit'
    end
  end
end

app/controllers/institution/notifications_controller.rb
class Institution::NotificationsController < Institution::BaseController

  def index
    @notifications = current_user.authenticable.notifications
  end

  def new
    @notification = Notification.new
  end

  def show
    @notification = Notification.find_by_slug params[:id]
  end

  def create
    @notification = Notification.new params[:notification]

    @notification.company = current_user.authenticable
    @notification.blood = Blood.where( name: @notification.blood_type).first

    position = current_user.authenticable.address.loc
    blood_types = BloodMatch.receives @notification.blood_type

    if blood_types
      people = GMap.elements_by_distance(position, @notification.distance.to_i, 'Person').map(&:addressable)
      for person in people
        last_participation = person.alerts.participateds.last
        next if last_participation && (last_participation.created_at + 3.months) > Time.now

        if person.blood.name.in? blood_types
          @notification.person_notifications.new person: person
        end
      end
    end

    if @notification.valid?
      if @notification.save
        redirect_to([:institution, :notifications], :notice => t('flash.notification.create.notice'))
      else
        render action: :new
      end
    else
      render action: :new
    end
  end

  def destroy
    @notification = Notification.find_by_slug params[:id]

    if @notification.destroy
      redirect_to [:institution, :notifications], :notice => t('flash.notification.delete.notice')
    else
      redirect_to :action => 'edit'
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  layout '/layouts/print', only: :print
  before_filter :authenticate_user!, only: [:confirm, :confirmed, :undo_confirm]

  def index
    if user_signed_in?
      @notifications = Notification.actives.compatibles_by(Blood.where(:name.in => BloodMatch.donor(current_user.authenticable.blood.name)).map(&:id)).paginate(:page => params[:page])
    else
      @notifications = Notification.actives.paginate(:page => params[:page])
    end
  end

  def show
    @notification = Notification.find_by_slug params[:id]
    @qr_code = RQRCode::QRCode.new( notification_url(@notification), :size => 10, leve: :l )
  end

  def confirm
    @notification = Notification.find_by_slug params[:id]
    @person = current_user.authenticable
    @person_notification = @notification.person_notifications.new
  end

  def confirmed
    @person = current_user.authenticable
    @notification = Notification.find_by_slug params[:id]

    if @notification.notification_confirmed( current_user.authenticable.id )
      update_notification_canceled
      redirect_to notifications_path
    else
      save_confirmed_notification
    end
  end

  def undo_confirm
    @notification = Notification.find_by_slug(params[:id])
    @person_notification = @notification.will_participate(current_user.authenticable)
    if @person_notification.update_attributes(canceled_at: Time.now)
      redirect_to notifications_path
    end
  end

  def list_user
    @notification = Notification.find_by_slug params[:notification_id]
    @person_notifications = @notification.person_notifications
  end

  def indication_friend
    @notification = Notification.find_by_slug params[:id]
    @send_indication = IndicationFriend.new
  end

  def send_indication
    @notification = Notification.find_by_slug params[:id]
    @send_indication = IndicationFriend.new params[:indication_friend]

    if @send_indication.valid?
      Mailer.indication_friend(@send_indication).deliver
      redirect_to notification_path(@notification)
    else
      render action: 'indication_friend'
    end
  end

  def print
    @notification = Notification.find_by_slug params[:notification_id]
    @qr_code = RQRCode::QRCode.new( notification_url(@notification), :size => 10, leve: :l )
  end

  private
    def save_confirmed_notification
      @person_notification = @notification.person_notifications.new params[:person_notification]

      if @person_notification.save
        redirect_to notification_path(@notification)
      else
        p @person_notification.errors
        render action: 'confirm'
      end
    end

    def update_notification_canceled
      @person_notification = @notification.will_participate(current_user.authenticable)

      if @person_notification.canceled?
        @person_notification.update_attributes(canceled_at: '')
      end
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def participate_button(notification)
    if user_signed_in?
      participate = notification.will_participate(current_user.authenticable)
      if participate.present? && participate.non_canceled?
        link_to t('buttons.non_participate'), undo_confirm_notification_path(notification), class: 'button red'
      else
        link_to t('buttons.participate'), confirm_notification_path(notification), class: 'button red'
      end
    else
      link_to t('buttons.participate'), confirm_notification_path(notification), class: 'button red'
    end
  end

  def show_list(count, notification)
    if count.zero?
      count
    else
      link_to count, notification_list_user_path(notification)
    end
  end

  def situations
    [
      ['Urgente', 'urgent'],
      ['Moderado', 'moderate']
    ]
  end

  def parse_time(time)
    time.strftime("%m de %b %Y - %H:%M h")
  end
end

app/views/notifications/_full_information.html.haml
#complete
  %h2 Obrigado por ajudar quem precisa!

  %span.thank
    A doação será realizada em #{parse_time(notification.created_at)}, no Hemocentro de #{notification.company.address.city} situado na #{notification.company.address.street}, #{notification.company.address.number}, #{notification.company.address.neighborhood}.
    %br
    A equipe Doando.se agradece por fazer parte desta corrente pela vida.
    %br
    Aguardamos a sua presença!


  = render partial: 'information', locals: { notification: notification, information: true }

  .action
    %span
      %b Antes de imprimir se concientize como  meio ambiente e utilize o QRCODE ou PDF.

    = link_to t('label.print'), notification_print_path(notification), target: '_blank',  class: 'button gray print'

app/views/notifications/_information.html.haml
#information_notification
  .information
    %span.label= t('label.blood')
    %span.text= notification.blood.name
    %span.label= t('label.quantity')
    %span.text= notification.quantity
    %span.label= t('label.situation')
    %span.text
      - for situation in situations
        = situation[0] if situation.include?(notification.situation)

    %span.label= t('label.alerted_at')
    %span.text= formated_date(notification.created_at)
    %span.label= t('label.company')
    %span.text= notification.company.name

  - if information
    .location
      %h3= t('label.address_company')

      %span.label= t('label.street')
      %span.text= notification.company.address.street
      %span.label= t('label.neighborhood')
      %span.text= notification.company.address.neighborhood
      %span.label= t('label.number')
      %span.text= notification.company.address.number
      %span.label= t('label.city')
      %span.text= notification.company.address.city
      %span.label= t('label.state')
      %span.text= notification.company.address.state
      %span.label= t('label.zip_code')
      %span.text= notification.company.address.zip_code

app/views/notifications/confirm.html.haml
#notification_confirm
  %h2= @notification.title

  = render partial: 'information', locals: { notification: @notification}

  #gmap

  = simple_form_for  @person_notification, :url => [:confirmed, @notification] do |f|
    = f.hidden_field :person_id, value: @person.id
    = f.hidden_field :notification_id, value: @notification.id
    = f.submit t('label.confirm'), class: 'button red'

  .show_instruction= link_to t('label.getting?'), @notification, class: 'button gray'

- content_for :javascript do
  :javascript

    Gmap.create({
      zoom: 10,
      center: new google.maps.LatLng(#{@notification.company.address.loc[0]}, #{@notification.company.address.loc[1]})
    })

    Marker.company(#{@notification.company.address.loc})

app/views/notifications/index.html.haml
#notifications
  %h1= t('views.notification.title')

  - unless @notifications.blank?
    - @notifications.each_with_index do |notification, index|
      -facebook_meta_for_notification notification
      .content_notifications
        .title
          %h2= notification.title
          .counter
            %b.count
              = show_list(notification.person_notifications.non_canceleds.count, notification)
            #{t('label.participant')} -
            #{t('label.remaining')}
            %b.remaining #{notification.remaining}


        = render partial: 'information', locals: { notification: notification}

        %div{ id: "gmap_#{index}", class: 'mini_map', 'data-lat' => notification.company.address.loc[0], 'data-lng' =>notification.company.address.loc[1]}

        .action
          = participate_button(notification)
          = link_to t('buttons.show'), notification, class: 'button gray'
          = link_to t('label.indicate'), indication_friend_notification_path(notification), class: 'button gray'
        .social
          .fb_share
            = facebook_share 'Compartilhe!', notification.slug
          .twitter_share
            - twitter_like notification_url(notification.slug), notification_twitt_label(true, notification), :hash_tags => ["doandose", notification.blood.name]

    = will_paginate @notifications

    - content_for :javascript do
      :javascript
        GmapList.list()

  - else
    .empty_list= t('label.empty')

app/views/notifications/indication_friend.html.haml
%h1= t('label.indicate')

#indicate

  = simple_form_for @send_indication, url: [:send_indication, @notification] do |f|
    .form
      = f.text_field :sender, placeholder: t('label.sender')
      = error_for(@send_indication, :sender)

      = f.text_field :email, placeholder: t('label.email')
      = error_for(@send_indication, :email)

      = f.text_field :subject, placeholder: t('label.subject'), value: subject
      = error_for(@send_indication, :subject)

      = f.text_area :message, placeholder: t('label.message'), value: message(@notification)
      = error_for(@send_indication, :message)

    .actions
      = f.button :submit, t('label.send'), class: 'button save'

app/views/notifications/list_user.html.haml
#list_user
  %h2= t('label.list_user')
  %span.title= @notification.title

  %span.top
    .line= t('label.name')
    .line= t('label.city')
    .line= t('label.state')
  - for person_notification in @person_notifications
    %span.body
      .line= truncate( person_notification.person.name, length: 15)
      .line= truncate( person_notification.person.address.city, length: 15)
      .line= truncate(  person_notification.person.address.state, length: 15)

app/views/notifications/print.html.haml
= render partial: 'notifications/full_information', locals:{ notification: @notification }
- content_for :javascript do
  :javascript
    $(document).ready(function(){
      window.print();
    })

app/views/notifications/show.html.haml
#notification_show
  - if current_user && @notification.will_participate( current_user.authenticable ).present? && @notification.will_participate( current_user.authenticable ).non_canceled?
    = render partial: 'full_information', locals: { notification: @notification}
  - else
    .title
      %h2= @notification.title
    = render partial: 'information', locals: { notification: @notification }

  %span.qrcode
    %span
      %b Acesse pelo celular.
    - qr_code(@qr_code)

  #gmap

  .social
    .fb_share
      = facebook_share 'Compartilhe!', @notification.slug
    .twitter_share
      - twitter_like notification_url(@notification.slug), notification_twitt_label(true, @notification), :hash_tags => ["doandose", @notification.blood.name]

  = render partial: '/shared/button_direction'
  #routePanel

- content_for :javascript do
  :javascript
    UserDirection.direction({ painel: 'routePanel' ,
                            destination: [#{@notification.company.address.loc[0]}, #{@notification.company.address.loc[1]}]})