config/routes.rb
Doandose::Application.routes.draw do
  mount Resque::Server.new, at: "/resque"

  root to: 'pages#index'

  match "/auth/:provider/callback" => "users/sessions#create"
  match '/auth/failure/' => 'users/sessions#failure'
  post '/send_email/' => 'send_mail#create', as: :send_mail
  post '/cadastro/email-em-uso/' => 'people#email_in_use'

  get '/quem_somos/' => 'pages#about_us', as: :about_us
  get '/depoimentos/' => 'testimonials#index', as: :testimonials

  namespace :users, :path => 'usuario' do
    match '/login' => 'sessions#new', as: :new_session
    match '/sair' => 'sessions#destroy', as: :destroy_session

    get  '/cadastro/' => 'identities#new', as: :new_user
    post '/cadastro/' => 'identities#create', as: :new_user
    get  '/meu-cadastro/' => 'identities#edit', as: :edit_user
    put  '/meu-cadastro/' => 'identities#update', as: :edit_user

    get '/esqueci-minha-senha/' => 'passwords#new', as: :new_password
    post '/esqueci-minha-senha/' => 'passwords#create', as: :new_password
    get '/esqueci-minha-senha/:token' => 'passwords#edit', as: :edit_password
    put '/esqueci-minha-senha/:token' => 'passwords#update'
  end

  post '/find_elements_to_map/' => 'gmap#find_elements_to_map'
  post '/find_elements_to_notification/' => 'gmap#find_elements_to_notification'

  resources :people, path: 'usuario' do
    get ':id/page/:page', action: :show, on: :collection
  end

  resources :pages, only: [:index, :show]

  resources :notifications, only: [:index, :show], path: 'notificacoes' do
    get 'page/:page', action: :index, on: :collection
    get :list_user
    get :print
    member do
      get :indication_friend
      post :send_indication
      get :confirm
      get :undo_confirm
      post :confirmed
    end
  end

  resources :campaigns, only: [:index, :show], path: 'campanhas' do
    get 'page/:page', action: :index, on: :collection
    get :print
    member do
      get :undo_confirm
      post :confirmed
    end
  end

  resources :person_notification, only: :index do
    member do
      get :canceling
    end
  end
  resources :companies, only: [:index, :show]
  resources :informations, only: [:show]

  namespace :admin do
    root :to => 'companies#index'
    match '/sair/' => 'base#destroy', as: :destroy_session
    post '/estatistica/cadastro-por-dia/' => 'statistics#subscribe_per_date'
    resources :pages, only: :index
    resources :companies
    resources :bloods
    resources :notifications
    resources :people, except: [:new, :create]
    resources :informations
    resources :campaigns
    get '/estatisticas/' => 'statistics#index', as: :statistics
  end

  namespace :institution, path: 'instituicao' do
    root :to => 'notifications#index'
    get '/sair/' => 'base#destroy', as: :destroy_company_session
    resources :notifications
    resources :campaigns, except: :destroy
    resources :person_notifications, only: :show do
      member do
        post :participation
        post :send_sms
        post :send_email
      end
    end
  end



end

app/models/person.rb
class Person
  # Includes
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slugify

  # Fields
  field :donor, type: Boolean
  field :name, type: String
  field :surname, type: String
  field :sex, type: String
  field :weight, type: Float
  field :height, type: Float
  field :birthday, type: Date
  field :observations, type: String

  # Access control
  attr_accessible :sex, :donor, :name, :surname, :weight, :height, :birthday,
    :observations, :address_attributes, :contact_attributes, :user_attributes,
    :blood, :blood_id

  # Relationships
  belongs_to :blood
  has_many :person_notifications, dependent: :destroy, autosave: true
  has_many :person_campaigns, dependent: :destroy, autosave: true
  has_many :alerts, dependent: :destroy, autosave: true
  has_one :address, as: :addressable, dependent: :destroy, autosave: true
  has_one :contact, as: :contactable, dependent: :destroy, autosave: true
  has_one :user, as: :authenticable, dependent: :destroy, autosave: true
  accepts_nested_attributes_for :address, :contact, :user, allow_destoy: true

  # Validations
  validates_inclusion_of :donor,  in: [true, false]
  validates_inclusion_of :sex,  in: %(f m)
  validates_presence_of :name, :weight, :height, :surname, :sex, :birthday,
    :contact, :address, :blood, :user
  validates_length_of :name, in: 2..30
  validates :weight, :height, numericality: true

  # Scopes
  scope :actives, where(active: true)
  scope :donors, where(donor: true)

  # Others
  def blood_donors
    BloodMatch.donor(blood.name)
  end

  def is_man?
    self.sex == 'm'
  end

  def birthdate=value
    super value
  rescue
    nil
  end

  private
  def generate_slug
    name.parameterize
  end
end

app/controllers/admin/people_controller.rb
class Admin::PeopleController < Admin::BaseController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find_by_slug params[:id]
  end

  def edit
    @person = Person.find_by_slug params[:id]
  end

  def update
    @person = Person.find_by_slug params[:id]

    if @person.update_attributes params[:person]
      update_user_cookie @person.user
      redirect_to([:admin, @person], :notice => t('flash.person.update.notice'))
    else
      render :action => "edit"
    end
  end

  def destroy
    @person = Person.find_by_slug params[:id]
    if @person.destroy
      redirect_to [:admin, :people], :notice => t('flash.person.delete.notice')
    else
      redirect_to :action => 'edit'
    end
  end
end

app/controllers/people_controller.rb
# encoding: utf-8
class PeopleController < ApplicationController
  before_filter only: :update do |c|
    c.send(:update_user_password_with_nested_fields, :person)
  end

  before_filter :authenticate_user!, only: [:show, :edit, :update]

  def new
    if current_user
      redirect_to edit_person_path(current_user.authenticable)
    else
      @person = Person.new
    end
  end

  def show
    @person = current_user.authenticable
    @person_notifications = @person.person_notifications.non_canceleds.paginate( per_page: 3, page: params[:page])
  end

  def create
    @person = Person.new(params[:person])

    if @person.save
      login @person.user
      redirect_to root_path
    else
     render action: 'new'
    end
  end

  def edit
    @person = current_user.authenticable
    @user = current_user
    @authentications = User.social_networks(@user)
  end

  def update
    @person = Person.find_by_slug params[:id]

    if @person.update_attributes(params[:person])
      update_user_cookie(@person.user)
      redirect_to person_path(@person), notice: t('flash.people.update.notice')
    else
      render action: :edit
    end
  end

  def email_in_use
    email = true if user_signed_in? && current_user.email == params[:email]
    email = !User.where(:email => /^#{params[:email]}/i).first if email.blank?
    render :json => email
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def setup_people(person)
    person.tap do |c|
      c.build_user if c.user.blank?
      c.build_address if c.address.blank?
      c.build_contact if c.contact.blank?
    end
  end

  def path_locale(attribute)
    t("label.user.confirmation_step.#{attribute}")
  end

  def people_markers
    markers = []
    Person.actives.all.map(&:address).each do |address|
      markers << address.full_coordinate if address.full_coordinate
    end
    markers
  end

  def people_sexes
    [
      ['Masculino', 'm'],
      ['Feminino', 'f'],
    ]
  end

  def formated_birthdate(birthdate)
    unless birthdate.blank?
      birthdate.strftime('%d/%m/%Y')
    else
      ''
    end
  end
end

app/views/admin/people/edit.html.haml
%h2= t('views.people.title_edit')

= render 'form'

app/views/admin/people/index.html.haml
#index
  %h2= t('views.people.title_index')

  - unless @people.blank?
    %table.list
      %thead
        %tr
          %th= t('label.donor')
          %th= t('label.name')
          %th= t('label.sex')
          %th= t('label.actions')

      %tbody
        - @people.each do |person|
          %tr
            %td= person.donor
            %td= person.name
            %td= person.sex
            %td
              = link_to t('buttons.show'), admin_person_path(person), class: 'link show'
              = link_to t('buttons.edit'), edit_admin_person_path(person), class: 'link edit'
              = link_to t('buttons.delete'), [:admin, person], method: :delete, confirm: t('flash.advertise'), :class => "link delete"

  - else
    .empty= t('label.empty')

- content_for :javascript do
  :javascript
    new Tables()

app/views/admin/people/show.html.haml
#show
  %h2= @person.name

  .content
    %p
      = label_boolean(@person.donor)
      %b= t('label.donor')

    %p
      = @person.name
      %b= t('label.name')

    %p
      = @person.surname
      %b= t('label.surname')

    %p
      = @person.sex
      %b= t('label.sex')

    %p
      = @person.weight
      %b= t('label.weight')

    %p
      = @person.height
      %b= t('label.height')

    %h2= t('label.address')

    - if @person.address
      %p
        = @person.address.street
        %b= t('label.street')

      %p
        = @person.address.number
        %b= t('label.number')

      %p
        = @person.address.neighborhood
        %b= t('label.neighborhood')

      %p
        = @person.address.city
        %b= t('label.city')

      %p
        = @person.address.state
        %b= t('label.state')

      %p
        = @person.address.zip_code
        %b= t('label.zip_code')

    %h2= t('label.contact')

    - if @person.contact

      %p
        = @person.contact.phone
        %b= t('label.phone')

      %p
        = @person.contact.cellphone
        %b= t('label.cellphone')

      %p
        = @person.contact.email
        %b= t('label.email')

    - if @person.user
      %p
        = @person.user.email
        %b= t('label.email')

  .actions

    = link_to t('buttons.back'), admin_people_path, :class => 'link back'

    = link_to t('buttons.edit'), edit_admin_person_path(@person), :class => 'link edit'

    = link_to t('buttons.delete'), [:admin, @person], method: :delete, confirm: t('flash.advertise'), :class => "link delete"